### ISSUE TITLE
input issue: does fastq_preprocessor support single end short reads?

### ISSUE THREAD

**Issue by chuanfaliu** [jolespin/fastq_preprocessor#1]
hi, Josh. I would like to know if the fastq_preprocessor tool supports the processing of single-end short reads. if true, could you provide an example of how to use the fastq_preprocessor tool with single-end reads? thanks a lot.

**Comment by jolespin** [comment]
Should be in the documentation but just do `fastq_preprocessor short -1 /path/to/r1.fq.gz -2 /path/to/r2.fq.gz -n name -o output_directory`

Can you describe your input issue?

**Comment by jolespin** [comment]
Though you can try using fastp, that's what is used in the backend. https://github.com/OpenGene/fastp

**Comment by chuanfaliu** [comment]
thank you very much for your kind reply.

**Comment by jolespin** [comment]
No problem.  Good luck!
